### ISSUE TITLE
json data `createdAt` and `updatedAt` is not compliant with API's iso-8601 date format

### ISSUE THREAD

**Issue by digitalsatori** [tzemanovic/haskell-yesod-realworld-example-app#2]
running Api provided  run-api-tests.sh script and got AssertionError for the date format.
I guess this is the related aeson issue: https://github.com/bos/aeson/issues/620

**Comment by tzemanovic** [comment]
Yep, the tests fail despite the timestamps having a ISO-8601 format. 

I've opened a PR to improve the tests https://github.com/gothinkster/realworld/pull/260, with these changes the tests do pass. Previously, they were just converting them to JS Date and back using `toISOString`, but that removes the extra precision and hence don't match the originals.

**Comment by digitalsatori** [comment]
Thanks for the explaination. just realized that ISO-8601 can represent datetime with *arbitrary* precision. The one generated by your system is totally valid in terms of ISO-8601 format.
